# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VZFlexlayout-Demo' do
	pod 'Vizzle'
	pod 'SDWebImage'
	pod 'VZInspector'
	pod 'VZFlexLayout', :path=>'../'

end
